### ISSUE TITLE
Unable to download files

### ISSUE THREAD

**Issue by Rehaell** [linuxserver/davos#23]
Hi,

I've installed davos on my homeserver, it connects perfectly to the remote server and lists the directories, but when it starts downloading it always throws an exception on a random folder and never actually downloads anything.

I have:
- Remove server on port 22 (SFTP)
- home server (UnRaid) with a docker of davos installed
- WD My book live, mounted on the UnRaid server and passed on to the davos container

Below is a snippet of the debug log, and also all the directories exist in both the remote and local server.

I've tried to use a different folder and the issue is still there.

```Listed 10 items from remote directory /home2/nctc25esj1/Media/Series/XTV/
2017-10-01 11:06:06.564 - DEBUG - [SFTPConnection] - Creating new local directory /Media/Series/XTV/
2017-10-01 11:06:06.564 - DEBUG - [FileUtils] - Directory was not created!
2017-10-01 11:06:06.565 - DEBUG - [SFTPConnection] - FTPFile[name=season01-poster.jpg,size=50266,path=/home2/nctc25esj1/Media/Series/XTV/,lastModified=2017-10-01T03:09:49.000+04:00,directory=false]
2017-10-01 11:06:06.565 -  INFO - [SFTPConnection] - Downloading /home2/nctc25esj1/Media/Series/XTV/season01-poster.jpg to /Media/Series/XTV/
2017-10-01 11:06:06.565 - DEBUG - [SFTPConnection] - Performing channel.get from /home2/nctc25esj1/Media/Series/XTV/season01-poster.jpg to /Media/Series/XTV/
2017-10-01 11:06:06.565 - DEBUG - [SFTPConnection] - Progress listener has been enabled
2017-10-01 11:06:06.694 - ERROR - [DownloadFilesWorkflowStep] - Unable to complete download. Error was: Unable to download file /home2/nctc25esj1/Media/Series/XTV
2017-10-01 11:06:06.695 - DEBUG - [DownloadFilesWorkflowStep] - Stacktrace
io.linuxserver.davos.transfer.ftp.exception.DownloadFailedException: Unable to download file /home2/nctc25esj1/Media/Series/XTV
        at io.linuxserver.davos.transfer.ftp.connection.SFTPConnection.download(SFTPConnection.java:66) ~[classes!/:?]
        at io.linuxserver.davos.schedule.workflow.transfer.FilesAndFoldersTranferStrategy.transferFile(FilesAndFoldersTranferStrategy.java:28) ~[classes!/:?]
        at io.linuxserver.davos.schedule.workflow.DownloadFilesWorkflowStep.runStep(DownloadFilesWorkflowStep.java:50) [classes!/:?]
        at io.linuxserver.davos.schedule.workflow.FilterFilesWorkflowStep.runStep(FilterFilesWorkflowStep.java:69) [classes!/:?]
        at io.linuxserver.davos.schedule.workflow.ConnectWorkflowStep.runStep(ConnectWorkflowStep.java:36) [classes!/:?]
        at io.linuxserver.davos.schedule.workflow.ScheduleWorkflow.start(ScheduleWorkflow.java:44) [classes!/:?]
        at io.linuxserver.davos.schedule.RunnableSchedule.run(RunnableSchedule.java:43) [classes!/:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_131]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_131]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: com.jcraft.jsch.SftpException:
        at com.jcraft.jsch.ChannelSftp.get(ChannelSftp.java:980) ~[jsch-0.1.50.jar!/:?]
        at com.jcraft.jsch.ChannelSftp.get(ChannelSftp.java:878) ~[jsch-0.1.50.jar!/:?]
        at io.linuxserver.davos.transfer.ftp.connection.SFTPConnection.doGet(SFTPConnection.java:114) ~[classes!/:?]
        at io.linuxserver.davos.transfer.ftp.connection.SFTPConnection.downloadDirectoryAndContents(SFTPConnection.java:145) ~[classes!/:?]
        at io.linuxserver.davos.transfer.ftp.connection.SFTPConnection.download(SFTPConnection.java:61) ~[classes!/:?]
        ... 13 more
Caused by: java.io.FileNotFoundException: /Media/Series/XTV (No such file or directory)
        at java.io.FileOutputStream.open0(Native Method) ~[?:1.8.0_131]
        at java.io.FileOutputStream.open(FileOutputStream.java:270) ~[?:1.8.0_131]
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213) ~[?:1.8.0_131]
        at java.io.FileOutputStream.<init>(FileOutputStream.java:101) ~[?:1.8.0_131]
        at com.jcraft.jsch.ChannelSftp.get(ChannelSftp.java:956) ~[jsch-0.1.50.jar!/:?]
        at com.jcraft.jsch.ChannelSftp.get(ChannelSftp.java:878) ~[jsch-0.1.50.jar!/:?]
        at io.linuxserver.davos.transfer.ftp.connection.SFTPConnection.doGet(SFTPConnection.java:114) ~[classes!/:?]
        at io.linuxserver.davos.transfer.ftp.connection.SFTPConnection.downloadDirectoryAndContents(SFTPConnection.java:145) ~[classes!/:?]
        at io.linuxserver.davos.transfer.ftp.connection.SFTPConnection.download(SFTPConnection.java:61) ~[classes!/:?]
        ... 13 more
2017-10-01 11:06:06.700 -  INFO - [DownloadFilesWorkflowStep] - Clearing current queue and will still continue to next step
2017-10-01 11:06:06.701 - DEBUG - [SFTPClient] - Disconnecting from channel
2017-10-01 11:06:06.701 - DEBUG - [SFTPClient] - Disconnecting from session
```

**Comment by j0nnymoe** [comment]
I suspect this is a permissions issue between the unraid server + the my book. Could you try saving locally to the unraid box instead?

**Comment by Rehaell** [comment]
@j0nnymoe i suspected the same thing, but the issue that the other containers write just fine.

Anyway, I'll test it tonight and update this.

Thanks

**Comment by JAGFin1** [comment]
Hi @Rehaell, this looks like a mapping issue between the container and your host filesystem. I can see that davos is attempting to create a new folder called "/Media/Series/XTV" but immediately fails. This is because there is no "/Media" directory inside the container. 

All downloads need to be put in the "/download" directory when using davos in docker. Your "docker create" command should have the following volume mapping in it:

"-p /Media:/download"

After which, in davos, use "/download" as your local directory. That way, all downloads will end up in "/Media" on the host filesystem.

**Comment by JAGFin1** [comment]
Closing this issue. If you're still having problems, please re-open it.
